### ISSUE TITLE
Communication Relay

### ISSUE THREAD

**Issue by Pixeltheaertist** [Pixeltheaertist/Trieste-Port-14#58]
A device that, as long as it's active, makes all radio messages LongRange or something similar, meaning that Sweetwater and Trieste can communicate as long as it's powered, active and intact.

There will be two of these. One on each map.

**Comment by lule345** [comment]
compiling from [this conversation on discord](https://discord.com/channels/1253266481093808140/1253266481811292183/1300609001435824281), comms system will essentially stay the same as of right now, but we'll introduce a "comms relay" where it'll be a small little hut sort of a little bit outside the comms room, where it connects the platform to sweetwater and vice versa via a cable (which you cant see as its vertical). by destroying the relay on either level, it disconnects both level's comms from each level, so one or the other cant contact each other. obviously it'll be guarded with like fences and stuff or something because antags but either way the concept's there.

also concept of implementing PDA messaging exists but im not sure whether to make it an issue or not if its too far-fetched

**Comment by Pixeltheaertist** [comment]
i believe how it will work currently, due to my brain being able to only do so much, is it _should_ (i haven't been able to test the branch yet) basically check if a relay is active, and if it is it'll make all transmissions on that map long range. I do think that means that if 

Sweetwater's relay is down but Trieste's is still up: Sweetwater can hear Trieste's radio messages, but not respond.

I'll try to fix it in the future, but i think this is as good as i can get for now. I still gotta test the current system.

**Comment by Pixeltheaertist** [comment]
it's a signal booster, meaning it captures radio signals and propagates them further, so i guess it sort of makes sense. Trieste's relay would still be boosting the frequencies down to sweetwater, but sadly sweetwater can't boost their own back up

**Comment by lule345** [comment]
probably yeah, one way comms relay sounds alright. also off-topic: let me
scan the RAS design thing i had rq before i forget

**Comment by Pixeltheaertist** [comment]
![image](https://github.com/user-attachments/assets/653440a7-7e71-4489-bc16-af028d48ca46)
ex: the communications relay from Rainworld

**Comment by Pixeltheaertist** [comment]
all we need now is a sprite

**Comment by lule345** [comment]
Copy, send me ideas via DM 


Sent from my Apple Watch
